# Generated by Django 2.1.7 on 2019-04-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=15)),
                ('ecard', models.IntegerField()),
                ('efname', models.CharField(max_length=64)),
                ('elname', models.CharField(max_length=64)),
                ('eagency', models.CharField(max_length=64)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Employee12',
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
